
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-happycows-f24-11
owner: ucsb-cs156-f24
repo_name: proj-happycows-f24-11
pull_requests: [{"author":{"id":"U_kgDOBtZIvw","is_bot":false,"login":"adenjo6","name":"Aden Jo"},"headRefName":"aden-CRUDOperationsCourses","number":38,"title":"ALL CRUD operations for courses (admin only)","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-11/pull/38"},{"author":{"id":"MDQ6VXNlcjQzMTU1MjY4","is_bot":false,"login":"smmzhu","name":"Samuel Zhu"},"headRefName":"sam-post","number":31,"title":"Added Post Endpoint for single record in students table","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-11/pull/31"},{"author":{"id":"MDQ6VXNlcjQzMTU1MjY4","is_bot":false,"login":"smmzhu","name":"Samuel Zhu"},"headRefName":"sam-ctrlr","number":30,"title":"Create StudentsController.java, add GetById Endpoint for single record in students table","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-11/pull/30"},{"author":{"id":"MDQ6VXNlcjY4MzEyNjY0","is_bot":false,"login":"blobthebuilder","name":"Frank Wang"},"headRefName":"Frank-FixProfitTableWidth","number":29,"title":"fix width","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-11/pull/29"},{"author":{"id":"MDQ6VXNlcjQzMTU1MjY4","is_bot":false,"login":"smmzhu","name":"Samuel Zhu"},"headRefName":"sam-newpsqltable","number":28,"title":"Created Postgres table json config, entity and repository for Students Table","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-11/pull/28"}]
