
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-happycows-f24-11
owner: ucsb-cs156-f24
repo_name: proj-happycows-f24-11
pull_requests: [{"author":{"id":"MDQ6VXNlcjY4MzEyNjY0","is_bot":false,"login":"blobthebuilder","name":"Frank Wang"},"headRefName":"Frank-ProfitsTableNew","number":20,"title":"closes #8","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-11/pull/20"},{"author":{"id":"U_kgDOBtZIvw","is_bot":false,"login":"adenjo6","name":"Aden Jo"},"headRefName":"aden-manageCowsNote","number":19,"title":"Minor UX Fix: Make explanation of buying and selling cows neater","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-11/pull/19"},{"author":{"id":"MDQ6VXNlcjQzMTU1MjY4","is_bot":false,"login":"smmzhu","name":"Samuel Zhu"},"headRefName":"sam-newlink","number":14,"title":"MINOR BUG FIX: Correct \"Mattanjah de Vries\" link","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-11/pull/14"},{"author":{"id":"MDQ6VXNlcjQzMTU1MjY4","is_bot":false,"login":"smmzhu","name":"Samuel Zhu"},"headRefName":"sam-caps","number":13,"title":"MINOR UX FIX: Inconsistent capitalization on Modal","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-11/pull/13"},{"author":{"id":"MDQ6VXNlcjY4MzEyNjY0","is_bot":false,"login":"blobthebuilder","name":"Frank Wang"},"headRefName":"Frank-ProfitTableWidth","number":12,"title":"Fix profit table width closes #8","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-11/pull/12"}]
