
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-happycows-f24-11
owner: ucsb-cs156-f24
repo_name: proj-happycows-f24-11
pull_requests: [{"author":{"id":"U_kgDOCM7SpA","is_bot":false,"login":"jonathanzhang2027","name":"JonathanZhang"},"headRefName":"OurTableBranch","number":55,"title":"Faster OurTable test","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-11/pull/55"},{"author":{"id":"MDQ6VXNlcjY2NDQ1ODIz","is_bot":false,"login":"brianc2730","name":"Brian Cheng"},"headRefName":"Brian-Announcements-DeleteButtonComponent","number":53,"title":"Added Frontend Delete Button Component and Modal Component for DELETE Operation for Announcements","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-11/pull/53"},{"author":{"id":"U_kgDOBtZIvw","is_bot":false,"login":"adenjo6","name":"Aden Jo"},"headRefName":"aden-PlaceholdersCourses","number":52,"title":"EDIT, INDEX, CREATE Pages for Courses plus tests plus Storybook","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-11/pull/52"},{"author":{"id":"U_kgDOBtZIvw","is_bot":false,"login":"adenjo6","name":"Aden Jo"},"headRefName":"aden-CoursesTable","number":51,"title":"(MERGE PR #50 BEFORE TOUCHING THIS) Table Component for Courses plus tests","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-11/pull/51"},{"author":{"id":"MDQ6VXNlcjY4MzEyNjY0","is_bot":false,"login":"blobthebuilder","name":"Frank Wang"},"headRefName":"Frank-PutEndpoint","number":41,"title":"Add Put Endpoint for Single Student","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-11/pull/41"}]
