
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-happycows-f24-11
owner: ucsb-cs156-f24
repo_name: proj-happycows-f24-11
pull_requests: [{"author":{"id":"MDQ6VXNlcjQzMTU1MjY4","is_bot":false,"login":"smmzhu","name":"Samuel Zhu"},"headRefName":"sam-test","number":57,"title":"test PR for jonathan","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-11/pull/57"},{"author":{"id":"U_kgDOCM7SpA","is_bot":false,"login":"jonathanzhang2027","name":"JonathanZhang"},"headRefName":"OurTableTestBranch","number":56,"title":"Faster OurTable frontend tests","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-11/pull/56"},{"author":{"id":"U_kgDOBtZIvw","is_bot":false,"login":"adenjo6","name":"Aden Jo"},"headRefName":"aden-PlaceholdersCourses","number":52,"title":"EDIT, INDEX, CREATE Pages for Courses plus tests plus Storybook","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-11/pull/52"}]
